### ISSUE TITLE
Outdated docker client failing to connect

### ISSUE THREAD

**Issue by cat5inthecradle** [drone/autoscaler#147]
Our drone infrastructure has been failing since the Docker 29 release, which appears to have rolled up the minimum client version.

```
error: "Error response from daemon: client version 1.40 is too old. Minimum supported API version is 1.44, please upgrade your client to a newer version"
```

**Comment by devkimittal** [comment]
Hey @cat5inthecradle we pushed a new tag drone/autoscaler:1.14.0, this has updated docker version. Can you please try with this image?

**Comment by kolaente** [comment]
I'm still seeing this with the latest drone autoscaler:

```json
{"error":"Error response from daemon: client version 1.24 is too old. Minimum supported API version is 1.44, please upgrade your client to a newer version","ip":"77.42.24.175","level":"debug","msg":"cannot connect, retry in 1m0s","name":"agent-PxN6vAYo","time":"2025-11-21T13:16:01Z"}

**Comment by devkimittal** [comment]
checking

**Comment by devkimittal** [comment]
pushed the image with CGO_ENABLED=1
can you please pull 1.14.0 again and try it?

**Comment by kolaente** [comment]
Now it starts again, but I still see the error in the logs and the runner is stuck in the `staging` state:

```json
{"error":"Cannot connect to the Docker daemon at https://77.42.24.175:2376. Is the docker daemon running?","ip":"77.42.24.175","level":"debug","msg":"cannot connect, retry in 1m0s","name":"agent-qaZ62reh","time":"2025-11-21T14:00:59Z"}

**Comment by cat5inthecradle** [comment]
We updated drone/autoscaler, but it looks like `drone/drone-runner-docker` is also behind.

https://github.com/drone-runners/drone-runner-docker/blob/master/go.mod#L5C1-L6C1

**Comment by devkimittal** [comment]
hey @cat5inthecradle thanks for raising the pr, we will soon upgrade the version.
Quick question, did you also face the issue that @kolaente is mentioning above? with drone/autoscaler:1.14.0 ?

**Comment by cat5inthecradle** [comment]
@devkimittal No, we only experienced the Docker API version mismatch issues.

**Comment by cat5inthecradle** [comment]
Is there any chance https://github.com/drone-runners/drone-runner-docker/blob/master/go.mod#L5C1-L6C1 could get the same fix?

**Comment by maxgruebneraeroqual** [comment]
We've also been pranked by this. 
Switching to the 1.14.0 docker image tag instead of latest resolved it for us.

**Comment by cat5inthecradle** [comment]
Since this [drone-runner-docker change](https://github.com/drone-runners/drone-runner-docker/pull/79) got merged, we've been able to switch back to the mainline `drone-runner-docker` image. This issue appears to be resolved.
